name: cinemate
description: "Free OpenSource TMDB client"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '3.6.2'
  flutter: '3.27.4'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  go_router: ^15.1.1
  smooth_page_indicator: ^1.2.0+3
  country_flags: ^3.2.0
  url_launcher: ^6.1.10
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.2
  http: ^1.3.0
  share_plus: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.14
  go_router_builder: ^2.7.1
  build_verify: ^3.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/img/
    - assets/img/icons/
    - assets/img/icons/navbar/
    - assets/img/icons/person/
    - assets/img/icons/profile/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTProBook.otf
          weight: 200
        - asset: assets/fonts/AvenirLTProRoman.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 400
        - asset: assets/fonts/AvenirLTProHeavy.otf
          weight: 700